### ISSUE TITLE
importing pyxdameraulevenshtein crashes python kernel

### ISSUE THREAD

**Issue by funkindy** [gfairchild/pyxDamerauLevenshtein#11]
Windows 10, Python 3.5, pyxdameraulevenshtein v1.5

I get "Kernel died, restarting" anytime i execute this line (in separate venv):

`import pyxdameraulevenshtein`

Seems like OS issue.

**Comment by gfairchild** [comment]
How did you install it? Did the pip install succeed?

**Comment by funkindy** [comment]
I have installed it vie pip as the dependency of textdistance package (i opened an issue there but they forwarded me here). So i just did this: 

`pip install textdistance[extras]`

to install. And it succeded.

**Comment by gfairchild** [comment]
Can you try installing `pyxdameraulevenshtein` by itself using pip and let me know if that works?

**Comment by gfairchild** [comment]
Would you mind creating a fresh virtual environment and installing with the following command?:

```
pip install --verbose pyxdameraulevenshtein
```

Please paste the contents of that output here so that I can get a little more insight into what's going on.

**Comment by funkindy** [comment]
@gfairchild i created fresh vene and installed with --verbose. Got this suspicious error:

--- Logging error ---
Traceback (most recent call last):
  File "c:\users\user\anaconda3\Lib\logging\__init__.py", line 983, in emit
    stream.write(self.terminator)
  File "c:\users\user\envs\new\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\users\user\envs\new\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\user\envs\new\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: raw write() returned invalid length 4 (should have been between 0 and 2)
Call stack:
  File "c:\users\user\anaconda3\Lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Envs\new\Scripts\pip.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\user\envs\new\lib\site-packages\pip\__init__.py", line 248, in main
    return command.main(cmd_args)
  File "c:\users\user\envs\new\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\user\envs\new\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\user\envs\new\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\user\envs\new\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\users\user\envs\new\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\users\user\envs\new\lib\site-packages\pip\wheel.py", line 273, in move_wheel_files
    logger.debug(stdout.getvalue())
Message: ''
Arguments: ()


But afterall "Successfully installed numpy-1.14.2 pyxdameraulevenshtein-1.5".

**Comment by gfairchild** [comment]
Is that the *complete* output of `pip install`?

Ok, so from what I can tell right now, it looks like the error is in the installation, not the use, of pyxdameraulevenshtein. We need to figure out how to be able to get you to install this on Windows. As indicated on the readme, you need to be able to compile C code. On Linux/Macs, this is easy. Using the Bash subsystem on Windows (which I'd *highly* recommend checking out if you haven't already), this is easy. I've never tried it on native Windows, though. Additionally, it looks like you're using Anaconda, which I've also never used, so I'm not sure how that affects things.

https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Build_Tools_for_Visual_Studio_2017_.28x86.2C_x64.2C_ARM.2C_ARM64.29 may be a good place to start. So, as those instructions say, try this:

1. Install [Microsoft Build Tools for Visual Studio 2017](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017).
1. `pip install --upgrade setuptools`
1. `pip install --verbose pyxdameraulevenshtein`

Let me know if that solves your problem.

**Comment by funkindy** [comment]
After i cloned the repo and installed from source (python setup.py install) i now get all the things work good. Also there is no crash on `import pyxdameraulevenshtein` as well. It is good in both clean venv and any existing venv as well.

So maybe the bug is somewhere in pypi version difference?

**Comment by gfairchild** [comment]
That's certainly interesting. The PyPI version is identical to master right now. Nothing has changed. So after trying what I just suggested, you still can't install from PyPI?

**Comment by gfairchild** [comment]
Very interesting. [NumPy should automatically be installed.](https://github.com/gfairchild/pyxDamerauLevenshtein/blob/master/setup.py#L93-L94), but that's clearly not the case. In fact, I just tried it on an empty virtual environment on my PC (using the Ubuntu subsystem on Windows 10), and I can replicate what you're referring to.

I need to fix `setup.py` so that NumPy is properly installed by pip if it's not already there. I'm currently essentially doing what https://stackoverflow.com/a/21621689/1269634 suggests, but that's clearly not working.

**Comment by gfairchild** [comment]
I just modified `setup.py` a bit to actually remove some checks. I've made the decision to expect the user to explicitly install NumPy prior to installing this library. 1.5.1 is now live on PyPI. I *think* this will fix your issue. Can you try and let me know?

**Comment by gfairchild** [comment]
1.5.2 was just released, which further addresses the NumPy dependency issue. I think this should solve your problem. I'm going to go ahead and close this issue, but please let me know if you're still experiencing this problem with 1.5.2.
