### ISSUE TITLE
numpy.dtype error

### ISSUE THREAD

**Issue by knwin** [gfairchild/pyxDamerauLevenshtein#17]
I am using Python2.7 of ArcGIS 10.5 (cannot update python version). Installed pyxDamerauLevenshtein (1.5.3) and numpy 1.16.2 in a virtual environment as ArcGIS use numpy 1.9.3 for its core moudles.
When I run, the script run under virtual environment but I got this error..

```
File "__init__.pxd", line 206, in init pyxdameraulevenshtein
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 56 from C header, got 52 from PyObject

```
_

**Comment by gfairchild** [comment]
I just tried creating a fresh Python 2.7 virtual environment to try this out, and I got no error:

```
~/projects/py2test$ virtualenv -p /usr/bin/python2.7 env
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/gfairchild/projects/py2test/env/bin/python2.7
Also creating executable in /home/gfairchild/projects/py2test/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
~/projects/py2test$ source env/bin/activate
(env) ~/projects/py2test$ pip install --upgrade pip setuptools wheel
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages (19.0.3)
Requirement already up-to-date: setuptools in ./env/lib/python2.7/site-packages (41.0.0)
Requirement already up-to-date: wheel in ./env/lib/python2.7/site-packages (0.33.1)
(env) ~/projects/py2test$ pip install pyxDamerauLevenshtein
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pyxDamerauLevenshtein
Collecting numpy>=1.16.1 (from pyxDamerauLevenshtein)
  Using cached https://files.pythonhosted.org/packages/c4/33/8ec8dcdb4ede5d453047bbdbd01916dbaccdb63e98bba60989718f5f0876/numpy-1.16.2-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: numpy, pyxDamerauLevenshtein
Successfully installed numpy-1.16.2 pyxDamerauLevenshtein-1.5.3
(env) ~/projects/py2test$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.version.version
'1.16.2'
>>> import pyxdameraulevenshtein
>>> exit()
```

Are you positive that you've got the right version of NumPy installed in the venv you're using? Can you repeat the same thing I just did above and show me your output?

**Comment by knwin** [comment]
Ys I installed numpy 1.16.2 in the virtual virtualenv. 
And just I found that, when I run, it imported the numpy from original location, of course older version, outside of virtual env that I cannot upgrade for compatibility with other modules. This happen when I run the script as ArcToolbox. How can I enforce to code to import the right numpy version?

It worked fine now when I run that virtual evn from outside of ArcGIS.

**Comment by gfairchild** [comment]
I'm glad you were able to get it working and that it's not a problem on this project's end.

Regarding how to enforce ArcGIS to use the right version of NumPy, I unfortunately can't really help you because I don't have ArcGIS to help with. Is there an ArcGIS forum you can post on to get help? What you really want is for ArcGIS to respect your local virtual environment.

**Comment by knwin** [comment]
Ys I have posted the question on http://stackoverflow.com/

The reason I am working with virtual environment is that ArcGIS has older numpy and pandas modules come along with ArcGIS installer. I am sure there are certain processing tools in ArcGIS that use these modules. And it does not allow me upgrade numpy and pandas unless it is in virtual environment.

I am creating a tool to match geographic names in databases/tables with standard names in a reference table. More over it will add standard codes (PCODE) for the names that will enable linking with other datasets from different sectors. If I can create a tool that will work on ArcGIS, standard name matching and PCODE insertion in spatial formats and spatial databases will be easier. 

I have also made a branch for creating a plugin for QGIS and it does not have such problem.

**Comment by gfairchild** [comment]
One alternative is that you could just compile pyxDL yourself in whatever environment ArcGIS uses. If you compile it yourself, it'll work against whatever version of NumPy ArcGIS includes. That's probably the simplest thing to do at this point.

**Comment by knwin** [comment]
Thanks for the advice. But I have not much knowledge on compiling modules except _pip install_. What will be the out come from such compilation? a .DLL file or .pyd?

**Comment by knwin** [comment]
Anyway I tried after some googling. but got error at end
![pyxCompileErr](https://user-images.githubusercontent.com/6437533/56414713-7ef17e80-62b1-11e9-993a-0f5021de6390.PNG)

**Comment by gfairchild** [comment]
Ah, you're on Windows - I unfortunately can't really help you with compilation on Windows. :(

**Comment by gfairchild** [comment]
@knwin, were you able to make any progress on this?

**Comment by knwin** [comment]
no luck. same error
it seems there is a conflict with arcgis core library. The codes run fine outside of ArcGIS in the same python installed by ArcGIS. 
`>>> execfile(r'C:\Python27\ArcGIS10.7\venv\pyxdl\Scripts\activate_this.py', {'__file__': r'C:\Python27\ArcGIS10.7\venv\pyxdl\Scripts\activate_this.py'})
>>> from pyxdameraulevenshtein import normalized_damerau_levenshtein_distance_ndarray as ndldn
Runtime error 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "__init__.pxd", line 206, in init pyxdameraulevenshtein
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 56 from C header, got 52 from PyObject
>>> `

**Comment by knwin** [comment]
Hi gfairchild,

since last time, I migrated to ArcGIS 10.7 but did not install pyxDL untill your message. I came back to github and read your instruction and I installed pyxDL in venv folder with pip. Then I installed Cython too. after the reply post above, I found some clues online that Cython cause this error. So unistalled it and it is working from inside ArcGIS.
Thanks.

**Comment by knwin** [comment]
![image](https://user-images.githubusercontent.com/6437533/60093153-bc213380-976e-11e9-95ae-7b7a890898a3.png

**Comment by gfairchild** [comment]
To be clear, you shouldn't actually need Cython. All Cython does is create the C file ([pyxdameraulevenshtein.c](https://github.com/gfairchild/pyxDamerauLevenshtein/blob/master/pyxdameraulevenshtein/pyxdameraulevenshtein.c)) from the pyx source ([pyxdameraulevenshtein.pyx](https://github.com/gfairchild/pyxDamerauLevenshtein/blob/master/pyxdameraulevenshtein/pyxdameraulevenshtein.pyx)). All you should need is a C compiler to compile the C file for Windows. I unfortunately don't have experience doing this (all of my Python development occur on a Mac or Linux system). However, https://docs.python.org/3/extending/windows.html or https://wiki.python.org/moin/WindowsCompilers might be good places to help figure this out.

**Comment by gfairchild** [comment]
Were you able to get this fixed?

**Comment by knwin** [comment]
I did not try to use it on ArcGIS after a few attempts. Instead I am using it as stand alone with geopandas to read spatial vector formats. I will try again on ArcGIS as I have upgraded to 10.7 and ArcGIS Pro.

**Comment by gfairchild** [comment]
I'm going to go ahead and close this issue. Please let me know if you continue to experience problems.
