### ISSUE TITLE
How to make edits to the source code 

### ISSUE THREAD

**Issue by kootenpv** [gfairchild/pyxDamerauLevenshtein#18]
Thanks, it is really cool!

I was trying to make an edit, but I cannot get any effect when I do:

    python setup.py install

I tried deleting all the source files in my virtualenv, including a .so file, but it doesn't make a difference.

Could you tell me what I can do to make a change to the `.pyx` and see the result in a built module?

**Comment by gfairchild** [comment]
Did you by chance forget to compile the changes you made to the `.pyx` file? My guess is that you need to go into `src/` and `cython pyxdameraulevenshtein.pyx`. This will compile the `.pyx` source into C source. Then, you should be able to run `python setup.py install`, which uses the `.c` source, *not* the `.pyx` source.

**Comment by gfairchild** [comment]
Were you able to get this fixed?

**Comment by kootenpv** [comment]
Yea i remember I got it to work! Your instructions helped I believe. Thanks.
