### ISSUE TITLE
Distance between "abc", "abcde" is 2 but between "abcde", "abc" is 1

### ISSUE THREAD

**Issue by BryanKoo** [gfairchild/pyxDamerauLevenshtein#24]
I appreciate that this implementation is a great help with array calculation !
I checked distances with simple strings.
I am afraid that I have strange distance calculation results.
 
damerau_levenshtein_distance('abcde', 'abc') = 1
damerau_levenshtein_distance('abc', 'abcde') = 2

**Comment by gfairchild** [comment]
Thanks for the report, @BryanKoo. I believe this is the same issue as #22. I'll try to get to this soon because it's definitely a bad bug.
