### ISSUE TITLE
Python 3.5 numpy support

### ISSUE THREAD

**Issue by Nikitafff** [gfairchild/pyxDamerauLevenshtein#25]
Hi! 
There is an update in numpy 1.19 that doesn't provide a support of Python 3.5. 

This line leads to an error in Python 3.5 because of trying to install new 1.19 version.
https://github.com/gfairchild/pyxDamerauLevenshtein/blob/master/setup.py#L82
These happens despite the strong equal of 1.16.1 numpy version in requirements.txt

Could you save the support of 3.5?

**Comment by gfairchild** [comment]
I'll look into this next week, but note that [Python 3.5 support ends in just a few months](https://www.python.org/downloads/), so I'm not sure if I'll want to actually change anything.

**Comment by gfairchild** [comment]
Yeah, in light of 3.5 support ending shortly, I've decided not to change anything in this project at this time.
