### ISSUE TITLE
ImportError: cannot import name 'damerau_levenshtein_distance_ndarray'

### ISSUE THREAD

**Issue by baharev** [gfairchild/pyxDamerauLevenshtein#30]
In the CHANGES.md I read:

> This is a breaking change if you currently rely on either of the `*_ndarray` methods.
> 
>     `damerau_levenshtein_distance_ndarray` refactored to `damerau_levenshtein_distance_seqs`

Simply claiming that you broke my code is not helpful. I noticed.

Please document better how you broke the code that relies on it.

Also, please provide a migration plan.

Thanks in advance.

**Comment by gfairchild** [comment]
Sorry about that. I'm a one-man development team (I take care of this project in my off-time for free), and the NumPy issue has been a challenge for a number of people for a while now. It was easier for me to remove it, and I don't have the resources to have a fancier migration plan.

**Comment by gfairchild** [comment]
Ok, I added a bit more detail in the changelog with examples of how to modify code for these new methods. Again, sorry about that.

**Comment by baharev** [comment]
OK, I understand. I did not mean anything fancy. Something like: rename `damerau_levenshtein_distance_ndarray` to `damerau_levenshtein_distance_seq`, and call `np.array()` with the return value to get the old behavior. Would this work?

I cannot try it myself at the moment. I messed up my environment due to this issue.

**Comment by gfairchild** [comment]
> OK, I understand. I did not mean anything fancy. Something like: rename `damerau_levenshtein_distance_ndarray` to `damerau_levenshtein_distance_seq`, and call `np.array()` with the return value to get the old behavior. Would this work?
> 
> I cannot try it myself at the moment. I messed up my environment due to this issue.

Sorry, I didn't mean for that to happen. Does the text I added in the changelog clarify?

**Comment by baharev** [comment]
OK, I see. My problem is with the returned value. As far as I can tell, that used to be an `np.array`. If I can convert the new returned value to an `np.array` by simply calling `np.array`, then it is a trivial change in the broken code. Unfortunately, I cannot try it now, sorry. So would this work?

Thanks!

**Comment by gfairchild** [comment]
> OK, I see. My problem is with the returned value. As far as I can tell, that used to be an `np.array`. If I can convert the new returned value to an `np.array` by simply calling `np.array`, then it is a trivial change in the broken code. Unfortunately, I cannot try it now, sorry. So would this work?
> 
> Thanks!

Ah, good point. Yes, simply passing the return value to an `np.array` will indeed fix it for you. I'll mention that in the changelog as well.

**Comment by baharev** [comment]
>  I'll mention that in the changelog as well.

Please do. That's all what I meant by migration plan: Rename the function to `damerau_levenshtein_distance_seqs`, and call np.array() with the returned value. It is a trivial change if it is documented.

Thanks!

**Comment by gfairchild** [comment]
> > I'll mention that in the changelog as well.
> 
> Please do. That's all what I meant by migration plan: Rename the function to `damerau_levenshtein_distance_seqs`, and call np.array() with the returned value. It is a trivial change if it is documented.
> 
> Thanks!

Done. It's all spelled out in the changelog now.

Thanks very much for the suggestions, and I apologize again for the unexpected breakage.

**Comment by baharev** [comment]
Thank you for the prompt reply and for this package!

**Comment by gfairchild** [comment]
> Thank you for the prompt reply and for this package!

My pleasure! Apologies again for the headache.
